-- AlterTable
ALTER TABLE "Business"
  ADD COLUMN IF NOT EXISTS "billingCycle" TEXT NOT NULL DEFAULT 'monthly',
  ADD COLUMN IF NOT EXISTS "billingCyclesCompleted" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "loyaltyDiscountIls" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "lastBillingReminderSentAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "walletBalanceIls" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "pendingYieldCampaign" JSONB;
