import type { ReactNode } from "react";
import type { Metadata } from "next";
import { Heebo, Karantina } from "next/font/google";
import { LanguageProvider } from "./lib/LanguageContext";
import "./globals.css";

const SITE_URL = "https://torionline.com";
const SITE_NAME = "תורי";
// OG/Twitter images and favicons are generated by the file conventions:
// opengraph-image.tsx, icon.svg, apple-icon.tsx — no static assets needed.

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "תורי | בוט WhatsApp AI לקביעת תורים אוטומטית",
    template: "%s | תורי",
  },
  description:
    "בוט WhatsApp חכם שקובע תורים אוטומטית, שולח תזכורות ומסנכרן לגוגל קלנדר. מתאים לסלוני שיער, קליניקות, ספרים ועוד. הקמה ב-10 דקות. נסה חינם.",
  keywords: [
    "הזמנת תורים אוטומטית",
    "בוט וואטסאפ",
    "קביעת תורים WhatsApp",
    "ניהול תורים סלון שיער",
    "WhatsApp Business בוט",
    "בוט תורים AI",
    "אוטומציה לסלון יופי",
    "קביעת תורים אינטרנט",
    "WhatsApp appointment bot",
    "appointment booking bot Israel",
  ],
  authors: [{ name: "תורי", url: SITE_URL }],
  creator: "תורי",
  publisher: "תורי",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "he_IL",
    alternateLocale: ["en_US"],
    url: SITE_URL,
    siteName: SITE_NAME,
    title: "תורי — בוט WhatsApp AI שקובע תורים אוטומטית",
    description:
      "הגדל הכנסות עם בוט AI שעונה ללקוחות 24/7 בוואטסאפ, קובע תורים ומסנכרן לגוגל קלנדר. ללא הכשרה, ללא כרטיס אשראי.",
  },
  twitter: {
    card: "summary_large_image",
    title: "תורי — בוט WhatsApp AI לקביעת תורים",
    description:
      "בוט AI שעונה ללקוחות בוואטסאפ, קובע תורים ומסנכרן לגוגל קלנדר — 24/7.",
    creator: "@torionline",
  },
  alternates: {
    canonical: SITE_URL,
    languages: {
      "he-IL": SITE_URL,
      "en-US": `${SITE_URL}/en`,
    },
  },
  category: "technology",
  classification: "Business Software",
};

const heebo = Heebo({
  subsets: ["hebrew", "latin"],
  variable: "--font-heebo",
  display: "swap",
});

const karantina = Karantina({
  weight: ["400", "700"],
  subsets: ["hebrew", "latin"],
  variable: "--font-karantina",
  display: "swap",
});

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="he" dir="rtl" suppressHydrationWarning className={`dark ${heebo.variable} ${karantina.variable}`}>
      <head>
        {/* Sync lang/dir from the saved preference before first paint, so the page never flashes
            the server default (Hebrew/RTL) before hydration corrects it for English users. */}
        <script
          dangerouslySetInnerHTML={{
            __html:
              "try{var l=localStorage.getItem('lang')||'he';document.documentElement.lang=l;document.documentElement.dir=l==='he'?'rtl':'ltr';}catch(e){}",
          }}
        />
      </head>
      {/* No bg-zinc-950/text-zinc-100 here: those were dark-theme leftovers that outranked the
          light `body` rule in globals.css (utilities beat @layer base). Nothing visible broke only
          because every page paints its own background and nearly every element sets its own text
          colour — but the inherited colour really was near-white on a light page, so anything added
          without an explicit colour would have rendered invisible. The pages that are still dark
          (password reset, OAuth callbacks) set their own background and text colours. */}
      <body className="min-h-screen font-[family-name:var(--font-heebo)]">
        <LanguageProvider>{children}</LanguageProvider>
      </body>
    </html>
  );
}
