ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "googleMapsUrl" TEXT;
ALTER TABLE "Appointment" ADD COLUMN IF NOT EXISTS "reminderSentAt" TIMESTAMP(3);
ALTER TABLE "Appointment" ADD COLUMN IF NOT EXISTS "reviewSentAt" TIMESTAMP(3);
