import type { PaymentProvider, PaymentCredentials, CreatePaymentLinkParams, PaymentLinkResult, VerifyResult } from "./types.js";
import {
  YPAY_BASE_URL,
  YPAY_RESPONSE_OK,
  ypayAccessToken,
  requestYpayToken,
  cacheYpayToken,
  ypayContactEmail,
} from "../ypayAuth.js";

/**
 * YPAY "Credit Clearing" (ypay.co.il). apiKey = client_id, apiSecret = client_secret — the SAME
 * pair the invoice adapter uses, which is why both go through ../ypayAuth.ts.
 *
 * Docs: https://ypay.co.il/assets/files/api/ypay_api_documentation.pdf (v1.9, 03-06-2025),
 * section "Credit Clearing".
 *
 * Worth knowing who is actually behind this: the URL their /payment endpoint returns is on
 * app.upay.co.il. YPAY resell UPay, the same processor PayPlus sit on top of. So this is not a new
 * acquirer for a salon — it is a second route to one they may already be using, whose selling
 * point is that clearing and the tax document come from one account instead of two.
 */

/** קבלה, generated by YPAY the moment the transaction succeeds. Deliberately the same document
 *  type the invoice adapter issues, so a salon moving between the two does not silently change
 *  which tax document its customers receive.
 *
 *  Not 0 ("none"), even though that would leave receipts to whichever invoice provider the salon
 *  connected. Their notify callback documents `sum` as present "only ... if 'docType' set on
 *  'Credit Clearing' is different than 'none'" — so asking for no document also throws away the
 *  amount, and the deposit webhook needs that amount to prove the payment covers what was owed. */
const DOC_TYPE_RECEIPT = 108;

/** Their maximum and default. Sent explicitly as 1 so a deposit is never quietly split — the field
 *  is optional and defaults to 12, which is the number of instalments the payer may CHOOSE. */
const SINGLE_PAYMENT = 1;

export const ypayPaymentProvider: PaymentProvider = {
  async createPaymentLink(creds: PaymentCredentials, params: CreatePaymentLinkParams): Promise<PaymentLinkResult> {
    const token = await ypayAccessToken(creds);
    const { email, synthetic } = ypayContactEmail(undefined, params.customerPhone, "open a payment page");

    const res = await fetch(`${YPAY_BASE_URL}/payment`, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
      body: JSON.stringify({
        // Mandatory, and unique per transaction. The appointment id doubles as YPAY's idempotency
        // key, which is exactly what it is used for on our side too.
        chargeIdentifier: params.referenceId,
        payments: SINGLE_PAYMENT,
        docType: DOC_TYPE_RECEIPT,
        mail: !synthetic,
        lang: "he",
        currency: "ILS",
        contact: {
          email,
          name: params.customerName ?? "לקוח",
          ...(params.customerPhone ? { mobile: params.customerPhone } : {}),
        },
        // vatIncluded, and no `name` — see the invoice adapter: a name files a new catalogue entry
        // in the salon's item index on every booking.
        items: [{ price: params.amountIls, quantity: 1, vatIncluded: true, description: params.description }],
        // Their notify payload carries success/transactionId/url/sum/document_id/document_type and
        // NOTHING that echoes chargeIdentifier back — so the reference has to ride on the URL we
        // hand them, or a paid deposit could never be matched to its appointment. Safe to put
        // there: the appointment id is already visible to the customer in the payment link, and
        // the webhook is authenticated by the secret in its path, not by this.
        ...(params.callbackUrl
          ? { notifyUrl: `${params.callbackUrl}?ref=${encodeURIComponent(params.referenceId)}` }
          : {}),
      }),
    });

    if (!res.ok) throw new Error(`YPAY payment page failed (${res.status}): ${await res.text()}`);
    const body = (await res.json()) as { url?: string; responseCode?: number; errorCode?: number; message?: string };
    if (body.responseCode !== YPAY_RESPONSE_OK) {
      throw new Error(`YPAY rejected the payment request (code ${body.errorCode ?? body.responseCode}): ${body.message ?? "unknown error"}`);
    }
    if (!body.url) throw new Error("YPAY response missing payment URL");

    // YPAY returns no transaction id here — one only exists once somebody pays, and it arrives on
    // the notify callback. Our own reference is the stable handle for the attempt, and it is what
    // the callback is correlated by anyway.
    return { paymentUrl: body.url, providerTransactionId: params.referenceId };
  },

  /**
   * Authenticating, rather than opening a ₪1 page as the other adapters do.
   *
   * A payment page would also work, but it consumes a chargeIdentifier and leaves an abandoned
   * transaction in the salon's YPAY account every time someone re-saves their keys. The token call
   * proves the same credentials with nothing left behind.
   *
   * Error 2002 ("There is already an active token for this user") is treated as VALID: only
   * working credentials can hold a live token, and reporting it as invalid would tell an owner
   * their correct keys were wrong precisely when they had just used them.
   */
  async verifyCredentials(creds: PaymentCredentials): Promise<VerifyResult> {
    try {
      const body = await requestYpayToken(creds);
      if (body.access_token) {
        cacheYpayToken(creds.apiKey, body.access_token, body.lifetime);
        return { valid: true };
      }
      if (body.errorCode === 2002) return { valid: true };
      return { valid: false, error: body.message ?? "Invalid client_id / client_secret" };
    } catch (err) {
      return { valid: false, error: err instanceof Error ? err.message : "Network error" };
    }
  },
};
